CREATE TABLE surgeries (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    session_number VARCHAR(255) NULL,
    session_date DATE NULL,
    theatre_request_date DATE NULL,
    full_name VARCHAR(255) NULL,
    patient_number VARCHAR(255) NULL,
    phone_numbers VARCHAR(255) NULL,
    theatre_room ENUM('Room1','Room2','Room3','Room4','Other') NULL,
    age INT NULL,
    scheduling_status ENUM(
        'SHA Submitted; Pending Approval',
        'Insurance Approved/Deposit Paid; Ready to Schedule',
        'Scheduled',
        'Completed',
        'Inactive',
        'SHA Rejected',
        'Cancelled'
    ) NOT NULL,
    booking_status VARCHAR(255) NULL,
    notes_comments TEXT NULL,
    diagnosis TEXT NULL,
    surgery TEXT NULL,
    urgent_cancer BOOLEAN NULL,
    surgery_type ENUM('Elective','Emergency','Minor','Major') NULL,
    surgery_category VARCHAR(255) NULL,
    proposed_date_of_surgery DATE NULL,
    date_of_surgery DATE NULL,
    payment_type ENUM('Cash','Other Insurance','Compassionate','SHA + Other','SHA') NULL,
    sha_procedure VARCHAR(255) NULL,
    sha_code VARCHAR(255) NULL,
    cpt_code VARCHAR(255) NULL,
    sha_approved_amount DECIMAL(12,2) NULL,
    sha_expiry_date DATE NULL,
    secondary_payer ENUM('AAP Insurance','Britam Insurance','First Assurance Insurance','GA Insurance','Jubilee Insurance','None') NULL,
    second_payer_approved_amount DECIMAL(12,2) NULL,
    length_of_surgery VARCHAR(255) NULL,
    date_deposit_paid DATE NULL,
    special_needs TEXT NULL,
    department ENUM('General Surgery','Orthopedics','Neurosurgery','Cardiology','Other') NULL,
    surgeon VARCHAR(255) NULL,
    deposit_amount DECIMAL(12,2) NULL,
    post_op_location ENUM('Ward','ICU','Recovery Room','Outpatient') NULL,
    requires_anesthesia_clearance BOOLEAN NULL,
    anesthesia_clearance_notes TEXT NULL,
    case_order VARCHAR(255) NULL,
    sha_eligible BOOLEAN NULL,
    icd10_code VARCHAR(255) NULL,
    department_additional ENUM('None','Radiology','Pathology','Anesthesiology') NULL,
    second_surgeon VARCHAR(255) NULL,
    attachments JSON NULL,
    appointment_id VARCHAR(255) NULL,
    entry_date DATE NULL,
    cancellation_reason TEXT NULL,
    cancellation_type VARCHAR(255) NULL,
    cancelled_at DATE NULL,
    created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
